"""Provider name constants."""

TRANSCRIPTION_WHISPER = "whisper"
TRANSCRIPTION_ASSEMBLYAI = "assemblyai"

DEFAULT_TRANSCRIPTION = TRANSCRIPTION_ASSEMBLYAI

# Backward-compatible aliases
TRANSCRIPTION_PROVIDER_WHISPER = TRANSCRIPTION_WHISPER
TRANSCRIPTION_PROVIDER_ASSEMBLYAI = TRANSCRIPTION_ASSEMBLYAI
DEFAULT_TRANSCRIPTION_PROVIDER = DEFAULT_TRANSCRIPTION
